when:
  - event: push
    branch: main
  - event: pull_request

steps:
  - name: lint
    image: python:3.11-slim
    commands:
      - pip install --upgrade pip
      - pip install flake8 black isort mypy
      - find . -name "*.py" -exec black --check {} \; || echo "No Python files found"
      - find . -name "*.py" -exec isort --check-only {} \; || echo "No Python files found"
      - find . -name "*.py" -exec flake8 {} \; || echo "No Python files found"
      - find . -name "*.py" -exec mypy {} \; || echo "No Python files found"

  - name: test
    image: python:3.11-slim
    commands:
      - pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - python -m pytest tests/ -v || echo "No tests directory found"
    depends_on:
      - lint

  - name: security
    image: python:3.11-slim
    commands:
      - pip install --upgrade pip bandit safety
      - find . -name "*.py" -exec bandit -r {} \; || echo "No Python files found"
      - safety check || echo "Safety check skipped"
    depends_on:
      - test

  - name: build
    image: python:3.11-slim
    commands:
      - echo "Build step - add your build commands here"
      - echo "Project built successfully"
    depends_on:
      - security

  - name: docs
    image: python:3.11-slim
    commands:
      - pip install --upgrade pip
      - pip install mkdocs mkdocs-material mkdocstrings[python] pymdown-extensions
      - if [ -d "DOCS" ] && [ -f "DOCS/mkdocs.yml" ]; then cd DOCS && mkdocs build --verbose; else echo "No MkDocs configuration found"; fi
    artifacts:
      when: always
      path: 
        - DOCS/site/**
    depends_on:
      - build

  - name: deploy
    image: python:3.11-slim
    commands:
      - echo "Deploy step - add your deployment commands here"
      - echo "Deployment completed"
    when:
      - event: push
        branch: main
    depends_on:
      - docs
